### ISSUE TITLE
Fix Deployment Preview with Netlify or use GitHub actions

### ISSUE THREAD

**Issue by jukent** [ProjectPythiaCookbooks/projectpythiacookbooks.github.io#25]
I followed @andersy005 's instructions [here](https://github.com/ProjectPythia/projectpythia.github.io/tree/main/Deployment-docs), but the Netlify deployment still doesn't seem to be working

I've added the GH secrets and the `preview.yml` file. I'm hoping to make any necessary changes [here](https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/blob/preview/.github/workflows/preview.yaml)

**Comment by jukent** [comment]
The only difference I've found between the portal and cookbooks gallery repositories is that there is a Heroku web app is enabled on the Portal

**Comment by kmpaul** [comment]
I'll take a look.

**Comment by brian-rose** [comment]
So the previews are still not working, e.g. in #38.

Options seem to be:
1. Fix whatever is broken with Netlify
2. Go with readthedocs instead, where previewing of Sphinx builds is nicely supported: https://docs.readthedocs.io/en/stable/pull-requests.html
3. Preview on GitHub pages using a version of the custom previewing capability I developed for Cookbook repos.

Personally I don't know how to proceed with Option 1. Option 2 may be straightforward. Option 3 I think I can get up and running pretty easily if there's consensus around that.

**Comment by kmpaul** [comment]
Personally, I think Netlify is problematic.  Netlify "projects" (or "sites") cannot be maintained by a team.  Only one person can have admin access to any Netlify site.  Currently, our sites are spread out over 3 administrators: @jukent (for the Cookbooks org), @andersy005 (for the main ProjectPythia org), and me (for the Tutorials org).  I don't think that's a sustainable option.

ReadTheDocs is a reasonable solution *for our main sites:* `projectpythia.org`, `foundations.projectpythia.org`, `cookbooks.projectpythia.org`, and `tutorials.projectpythia.org`.  However, I don't know if it is a sustainable solution for additional cookbooks.  Each cookbook repo would need to be added manually as a new "project" (or "subproject", if we want to share a domain across multiple projects).  I don't think that's sustainable.

So, that leaves Option 3.  @brian-rose, you mentioned that you have solved the "automatically create GitHub Pages previews for all new cookbook repos" problem, so I think this is the sustainable option for previews.  If we can demonstrate that methodology for the Cookbooks org and repos, then we can port the other repos/orgs to this approach.

**Comment by brian-rose** [comment]
> So, that leaves Option 3. @brian-rose, you mentioned that you have solved the "automatically create GitHub Pages previews for all new cookbook repos" problem, so I think this is the sustainable option for previews. If we can demonstrate that methodology for the Cookbooks org and repos, then we can port the other repos/orgs to this approach.

I think that we have *already* demonstrated this methodology for the Cookbook repos themselves (the [template repo](https://github.com/ProjectPythiaCookbooks/cookbook-template) and all the repos derived from it that house actual Cookbooks. It sounds like we should proceed with porting this approach to the [repo for cookbooks.projectpythia.org](https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io) so that, at least in the short term, we can have working previews for the Cookbook landing page.

If we're happy with that, we can then work on further porting the approach to our other main sites. Keeping everything consistent across our repos will hopefully mean less confusion and less maintenance.

**Comment by brian-rose** [comment]
Ok, I have now implemented option #3 here! You can see a working example of the preview in #52

@jukent can you now go through and deactivate the unneeded Netlify infrastructure?

**Comment by jukent** [comment]
I removed the Netlify secrets. Not sure if there was anything else.

**Comment by brian-rose** [comment]
> I removed the Netlify secrets. Not sure if there was anything else that wasn't already edited in the github workflows.

Ok, I just opened a new PR #54 and all the Netlify comments are still appearing. You may need to go into the Netlify site and "delist" this repo somehow. Or in other words reverse the steps in [Anderson's guide](https://github.com/ProjectPythia/projectpythia.github.io/tree/main/Deployment-docs)

**Comment by jukent** [comment]
The builds were stopped but I just deleted the site on Netlify too.

**Comment by jukent** [comment]
Hmm it is still in the PRs

**Comment by brian-rose** [comment]
There is no mention of `netlify` anywhere in the repo files, and there are no web hooks associated with this repository pointing to Netlify.

**Comment by brian-rose** [comment]
Maybe, like a hangover, it will just go away after a while.

**Comment by jukent** [comment]
Could it have to do with this page? https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/blob/main/.pre-commit-config.yaml `pre-commit-config` hasn't been edited for 10 days?

**Comment by jukent** [comment]
Hmm I had deleted the `projectpythiacookbooks` Netlify site. Now I realized everything was pointing to the `voluble-peony-e23e5f` site Netlify made for me by default. I've deleted that too and I think that should do it
