### ISSUE TITLE
Updated index.md file not rendered

### ISSUE THREAD

**Issue by clyne** [ProjectPythiaCookbooks/projectpythiacookbooks.github.io#34]
This [PR](https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/pull/28), which should update the intro paragraph [here](https://cookbooks.projectpythia.org/) was approved and merged, but the displayed text has not been updated. The displayed text is:

> Pythia Cookbooks provide example workflows on more advanced and domain-specific problems developed by the Pythia community. Cookbooks build on top of skills you learn in Pythia Foundations.

It should read:

> Pythia Cookbooks provide example workflows on more advanced and domain-specific problems developed by the Pythia community. Cookbooks build on top of skills you learn in Pythia Foundations.

> Cookbooks are created from Jupyter Notebooks that we strive to binderize so each Cookbook can be executed in the cloud with a single click from your browswer. See documentation [here](https://foundations.projectpythia.org/preamble/how-to-use.html#interacting-with-jupyter-notebooks-in-the-cloud-via-binder) for details. In some instances executing a Cookbook will require downloading the Notebook to your local laptop or desktop as described [here](https://foundations.projectpythia.org/preamble/how-to-use.html#interacting-with-jupyter-books-locally).

**Comment by brian-rose** [comment]
I think the reason is that the `index.md` is generated automatically by the gallery generator. The text seems to be hard-coded on this page: https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/blob/main/site/_extensions/cookbook_gallery_generator.py

@jukent is this correct?

**Comment by brian-rose** [comment]
https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/pull/38 would probably suffer from the same problem.

Is there a straightforward way to write that header text in its own `.md` file and have the generator use that, instead of trying to edit text strings in a `.py` file?

**Comment by jukent** [comment]
I will update the string to match this @clyne 

Perhaps a better solution is to have a .txt file that has the subtext which is then read in. Would that be less confusing?

**Comment by brian-rose** [comment]
> Perhaps a better solution is to have a .txt file that has the subtext which is then read in. Would that be less confusing?

Probably, but on the other hand I don't think it will matter that much. I don't expect we'll be editing that subtext frequently once we get things up and running.

**Comment by jukent** [comment]
I can do either way no problem. I drafted a PR using the file.
