### ISSUE TITLE
Need token for git authentication in workflow

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythiaCookbooks/projectpythiacookbooks.github.io#45]
The new cookbook gallery submission workflow needs permissions to push changes to the repo.  The action is currently failing when trying to push changes.

https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/runs/7243006662?check_suite_focus=true

**Comment by brian-rose** [comment]
This is most likely the same restriction that comes up with previewing. Some actions need to happen in a privileged context (i.e. be run from the repo itself, not from a user submitting an issue or PR).

The workaround that we use with the previews is to run the build, zip it, and upload as an artifact. Then a different workflow triggered by a `workflow_run` event runs the privileged action, where the artifact is downloaded and deployed.

See e.g. https://github.com/ProjectPythiaCookbooks/cookbook-template/blob/main/.github/workflows/deploy-preview.yaml
which runs with privileges after the book build is triggered.

**Comment by jukent** [comment]
Maybe we can work on this next week now that @brian-rose has the previews working as expected for a standard (non-bot opened) PR

**Comment by jukent** [comment]
I followed the steps here https://docs.github.com/en/actions/security-guides/automatic-token-authentication but it still isn't working. I wonder if I'm calling the token in the right place? I'm going to watch some videos and read some blogs on this to see if I missed something in the docs.

**Comment by jukent** [comment]
The GITHUB_TOKEN token has write permission in the set-up jobs section of the log
<img width="319" alt="Screen Shot 2022-07-13 at 2 41 05 PM" src="https://user-images.githubusercontent.com/46687291/178830498-0e6cd388-a272-4ba6-a058-7206574ec98e.png">

I tried to create a NEW_COOKBOOK_TOKEN. Maybe I'll rename it and see if that helps

**Comment by jukent** [comment]
"The [Personal Access Token (PAT)](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) should have repo scope. Additionally, if the upstream makes changes to the .github/workflows directory, the action will be unable to push the changes to a branch and throw the error "(refusing to allow a GitHub App to create or update workflow .github/workflows/xxx.yml without workflows permission)". To allow these changes to be pushed to the fork, add the workflow scope to the PAT. Of course, allowing this comes with the risk that the workflow changes from the upstream could run and do something unexpected. Disabling GitHub Actions in the fork is highly recommended to prevent this."

Not sure why there are chagnes to the .github/workflows directory
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md

I feel like I keep moving closer and further away from the solution, but I'm learning.

**Comment by jukent** [comment]
Working! I think I wasn't giving enough time between iterating on different methods.
