### ISSUE TITLE
CNAME file points to 

### ISSUE THREAD

**Issue by jukent** [ProjectPythiaCookbooks/projectpythiacookbooks.github.io#56]
[CNAME](https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/blob/main/CNAME) points to `tutorials.projectpythia.org`. Is this file doing anything? Should it point to `cookbooks.projectpythia.org`? Pinging @kmpaul because you edited this file.

**Comment by kmpaul** [comment]
I believe that is a remnant from when this repo was a fork of the tutorials repo. Yes. It should point to the cookbooks url.
