### ISSUE TITLE
Removing broken/template cookbooks from gallery

### ISSUE THREAD

**Issue by r-ford** [ProjectPythiaCookbooks/projectpythiacookbooks.github.io#82]
Now that we have a few cookbooks that mostly work (CESM LENS on AWS, CMIP6, HRRR AWS, and Radar), should we remove the entries that are currently only the template material (Packaging, XGCM) or broken (Physical Oceanography)? Maybe also the Matplotlib Colorbars cookbook, depending on overlap with [this recent merge in Foundations](https://github.com/ProjectPythia/pythia-foundations/pull/310).

**Comment by clyne** [comment]
I would opine that we either do not show cookbooks in the gallery that are known to be broken until we can fix them, or make use of the health check ("nightly-build") flag to indicate that they are broken in some way (but may still be useful to view).

**Comment by brian-rose** [comment]
I think we can differentiate between cookbooks that are "broken but partially useful" and ones that really have no content. I opine that the ones that have no actual content beyond the template material (even if they have some work-in-progress stuff in open PRs) should *not* appear in our gallery.

So yes, I opine that we should remove Packaging and XGCM cookbooks from the gallery *for now* and add them back in when they have some content merged in.

Related points in #41: we should have tagged releases of Cookbook source repos to coincide with the decision to "include them in the gallery"
and in https://github.com/ProjectPythiaCookbooks/cookbook-template/issues/53: our health checks need a more nuanced way to report failures in notebook execution.

**Comment by r-ford** [comment]
Done with #84
