### ISSUE TITLE
Removing mpl-colorbar-cookbook from the website

### ISSUE THREAD

**Issue by hCraker** [ProjectPythiaCookbooks/projectpythiacookbooks.github.io#83]
The mpl-colorbar-cookbook is [being archived](https://github.com/ProjectPythiaCookbooks/mpl-colorbar-cookbook/issues/13) because the information in it is better suited for the Project Pythia Foundations Page. The content has [already been moved](https://github.com/ProjectPythia/pythia-foundations/pull/310) to the foundations page, and now the cookbook needs to be removed from the website.

**Comment by r-ford** [comment]
Done with #84
