### ISSUE TITLE
Update infrastructure on all Cookbook repos to current template

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythiaCookbooks/projectpythiacookbooks.github.io#96]
Now that recent infrastructure work affecting the [cookbook template](https://github.com/ProjectPythiaCookbooks/cookbook-template) like https://github.com/ProjectPythiaCookbooks/cookbook-template/issues/89 and https://github.com/ProjectPythiaCookbooks/cookbook-template/issues/61 are done, it's time to get all the existing cookbook repos updated to use the latest infrastructure.

Repos that have already been updated include
- Radar Cookbook
- HRRR AWS Cookbook
- CMIP6 Cookbook

and maybe others.

**Comment by brian-rose** [comment]
Repos that most likely need updating include:

- [ ] https://github.com/ProjectPythiaCookbooks/cesm-lens-aws-cookbook
- [ ] https://github.com/ProjectPythiaCookbooks/test-cookbook
- [ ] https://github.com/ProjectPythiaCookbooks/gridding-cookbook
- [ ] https://github.com/ProjectPythiaCookbooks/xgcm-cookbook
- [ ] https://github.com/ProjectPythiaCookbooks/intake-cookbook
- [ ] https://github.com/ProjectPythiaCookbooks/packaging-cookbook
- [ ] https://github.com/ProjectPythiaCookbooks/physical-oceanography-cookbook

**Comment by brian-rose** [comment]
@jukent is this something you might be able to tackle?

**Comment by jukent** [comment]
> @jukent is this something you might be able to tackle?

Yes, but not until next week.

**Comment by jukent** [comment]
Should we close this now?

**Comment by brian-rose** [comment]
Yes! it's done.
